/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as CrRouteImport } from './routes/cr'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActivitiesRouteImport } from './routes/admin.activities'
import { Route as AdminOrganizationRouteImport } from './routes/admin.organization'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CrRoute = CrRouteImport.update({
  id: '/cr',
  path: '/cr',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationRoute = AdminOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/change-password': typeof ChangePasswordRoute
  '/cr': typeof CrRoute
  '/login': typeof LoginRoute
  '/teacher': typeof TeacherRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/calendar': typeof CalendarRoute
  '/change-password': typeof ChangePasswordRoute
  '/cr': typeof CrRoute
  '/login': typeof LoginRoute
  '/teacher': typeof TeacherRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/change-password': typeof ChangePasswordRoute
  '/cr': typeof CrRoute
  '/login': typeof LoginRoute
  '/teacher': typeof TeacherRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/admin'
    | '/calendar'
    | '/change-password'
    | '/cr'
    | '/login'
    | '/teacher'
    | '/admin/activities'
    | '/admin/organization'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/calendar'
    | '/change-password'
    | '/cr'
    | '/login'
    | '/teacher'
    | '/admin/activities'
    | '/admin/organization'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/admin'
    | '/calendar'
    | '/change-password'
    | '/cr'
    | '/login'
    | '/teacher'
    | '/admin/activities'
    | '/admin/organization'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  CrRoute: typeof CrRoute
  LoginRoute: typeof LoginRoute
  TeacherRoute: typeof TeacherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cr': {
      id: '/cr'
      path: '/cr'
      fullPath: '/cr'
      preLoaderRoute: typeof CrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organization': {
      id: '/admin/organization'
      path: '/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AdminOrganizationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminOrganizationRoute: typeof AdminOrganizationRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminOrganizationRoute: AdminOrganizationRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRouteWithChildren,
  CalendarRoute: CalendarRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  CrRoute: CrRoute,
  LoginRoute: LoginRoute,
  TeacherRoute: TeacherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
